### PR TITLE
Fix issue with stored request

### PR DESCRIPTION
**Pull request by gschwind**
Stored request was not restored correctly in the function
Process.launch_next_process, in particular "asReference" outputs aren't
"asReference" any more after being restored.

# Overview

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@gschwind Thanks for looking at this. Could you make a PR to the pywps-4.4 branch? We are still in the process to get the master/main working again (#568) ...

**Comment by gschwind** [comment]
Hello,

I have already looked at master, the master should not be affected by the bug because the code store request and process into the database.

I can have look to the branch pywps-4.4, but not immediately, maybe next week.

Best regards

**Comment by gschwind** [comment]
Hello,

I created a pull request for the branch pywps-4.4 and tested it: #579

Best regards

**Comment by cehbrecht** [comment]
Fixed in PR #579

**Pull request closed without merging**
