### PR TITLE
Fixed raising error of Maximum Request Size

### PR DESCRIPTION
**Pull request by eran-pinhas**
# Overview

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by jachym** [comment]
I've just done minor pep8 fix

**Comment by jachym** [comment]
@eran-pinhas could you please check the checkbox in your Contribution agreement in the PR template?

**Comment by eran-pinhas** [comment]
Checked the agreements

**Comment by jachym** [comment]
Thank you

**Pull request merged**
