### PR TITLE
drop py2 reqs

### PR DESCRIPTION
**Pull request by fmigneault**
# Overview

The bigger issue about desync master / pywps-4,2 branch remains, but at least pywps-4.2 branch can be installed without conflicting dependencies. 

# Related Issue / Discussion
#568 

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute #568 to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [ ] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
I would prefer to support only `python>=3.6`. 

`flufl.enum` has support for python 3.6 ... well ... by doing nothing.
https://pypi.org/project/flufl.enum/4.1.1/

Can we skip `enum34` and `pathlib` if we only support `py>=3.6`?

Dropping complete py2 support would go into the pywps 4.4 version.

**Review by cehbrecht — COMMENTED** [review]
see inline

**Comment by fmigneault** [comment]
I don't mind dropping their support. I'm also good with >=3.6 has this is the versions I use. 
The critical issue I face is that those libraries somehow get installed when they shouldn't. 
They end up overriding the ones in standard libs, which result in missing methods being raised.

**Comment by cehbrecht** [comment]
> I don't mind dropping their support. I'm also good with >=3.6 has this is the versions I use.
> The critical issue I face is that those libraries somehow get installed when they shouldn't.
> They end up overriding the ones in standard libs, which result in missing methods being raised.

I would only support Python >=3.6. Would you like to make this change so that it fits?

**Review by cehbrecht — APPROVED** [review]
see inline

**Comment by fmigneault** [comment]
@cehbrecht all done. 
I also added the `python_requires` for setup install. This will be reflected in pip packages/releases.

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@fmigneault looks good :smile: I will make a new 4.2 release ... hopefully the last one. The next one should be 4.4.

**Pull request merged**
