### PR TITLE
Include format information for "referenced" ComplexData

### PR DESCRIPTION
**Pull request by huard**
# Overview
Include more information about outputs in describeprocess. 

# Related Issue / Discussion
#410 

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard can you point me in the wps 1.0.0 spec where this is described?
http://www.opengeospatial.org/standards/wps

The spec is no fun to read :)

I have found `asReference` only in table 51 which belongs to the `Execute` response document.

The description of complex output for `DescribeProcess` response is in table 21.

**Comment by huard** [comment]
You're right, my mistake.

**Comment by jachym** [comment]
@huard I think, asReference does not belong to describeprocess - only execute response

**Comment by huard** [comment]
Right, the PR title was misleading. Fixed it.

**Pull request merged**
