### PR TITLE
update changes for 4.4.3

### PR DESCRIPTION
**Pull request by cehbrecht**
# Overview

Update changes for release 4.4.3.

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x ] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
Restricted sphinx <4 in this PR. See #608

**Comment by ldesousa** [comment]
Looks good. I see there is a new tag already. Is an announcement being prepared?

**Comment by cehbrecht** [comment]
> Looks good. I see there is a new tag already. Is an announcement being prepared?

@ldesousa I have uploaded 4.4.3 to pypi and conda package will be there soon. Would you like to do an announcement? It is only a patch release ...

**Comment by ldesousa** [comment]
@cehbrecht It would be good to put up an announcement through Twitter and/or the mail-list. I think even for patches it is important to keep the community informed. A more formal announcement can be reserved for major/minor releases.

**Comment by cehbrecht** [comment]
> @cehbrecht It would be good to put up an announcement through Twitter and/or the mail-list. I think even for patches it is important to keep the community informed. A more formal announcement can be reserved for major/minor releases.

@ldesousa would you like to make an announcement? The conda package is now also available ... nothing broken so far :)

**Pull request merged**
