### PR TITLE
set up requested mimetype of response

### PR DESCRIPTION
**Pull request by eran-pinhas**
set up the requested format as response.outputs[name].data_format

if the requested format is not in response.outputs[name].supported_formats - raise InvalidParameterValue error

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my 
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by eran-pinhas** [comment]
@cehbrecht - not an enhancement, it's bug (unless i got it all wrong). 

when the request specifies strictly what response mimetype it is expecting - the handler's response object is not being effected and therefore the handler is unable to answer with the right data

**Comment by eran-pinhas** [comment]
btw, why does the coveralls check fails?

**Comment by cehbrecht** [comment]
@eran-pinhas 

> btw, why does the coveralls check fails?

I suppose it needs to be configured to be less restrictive on the expected coverage. I would ignore it for now. 

@jachym Can you check the coverage config?

**Comment by cehbrecht** [comment]
I have tested this PR with my Emu service using the following request:

http://localhost:5000/wps?version=1.0.0&service=WPS&request=Execute&identifier=wordcounter&DataInputs=text=@xlink:href=http://bird-house.github.io&ResponseDocument=output=@asReference=True@mimetype=application/json

When I choose an invalid like `mimetype=image/png` I get with PR an exception (as expected):
_MimeType image/png not valid_

It looks like the `mimetype` attribute is not case-insensitive ... probably another issue.

**Comment by cehbrecht** [comment]
@eran-pinhas Thanks for fixing this. Maybe you could also extend the test-suite for this case? Otherwise I will pull it in.

**Comment by cehbrecht** [comment]
> > It looks like the mimetype attribute is not case-insensitive ... probably another issue.

> I don't understand, what is the issue?

if you use `mimeType` instead of `mimetype` in the above request to the wordcounter process then the mimetype is not recognized. It is not related to this PR ... just noticed while testing.

**Comment by eran-pinhas** [comment]
Done

**Comment by eran-pinhas** [comment]
yes it is sound simpler, thank you

**Pull request merged**
