### PR TITLE
updating misstypo in OGC WPS url

### PR DESCRIPTION
**Pull request by daviguima**
# Overview

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@daviguima you need to check "I like to contribube ..." in your issue text. 

@jachym This is a patch for pywps 3.2. Should we just accept?

**Comment by daviguima** [comment]
@cehbrecht is it ok now? sry for the trouble, I just wanted to help

**Comment by cehbrecht** [comment]
@daviguima merged. Thanks.

**Comment by jachym** [comment]
thank you

**Pull request merged**
