### PR TITLE
Check data is defined in literal template

### LINKED ISSUE #498: Literal template return DefaultValue when data is not defined
# Description

The describeProcess response includes an empty DefaultValue field, which OWSLib 0.18 chokes on. 

# Environment

- operating system: ubuntu
- Python version: 3.6
- PyWPS version: 4.2.2

### PR DESCRIPTION
**Pull request by huard**
# Overview
I think this started causing issues with owslib 0.18. 

# Related Issue / Discussion
Fixes #498 

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard merged. Thanks.

**Comment by tlvu** [comment]
Could a conda and pypi release be made to make this fix available? Thanks.
________________________________

**Comment by cehbrecht** [comment]
@tlvu does it help to use the master branch in your deployment?
https://github.com/bird-house/emu/blob/a307fdf5998623c2b9bf5f5e08fe908c4b4bc03a/environment.yml#L18

We don't have so many fixes since the last release ... 

@jachym @tomkralidis 
Would you mind to do a 4.2.3 release or should we wait?

**Comment by jachym** [comment]
If @tlvu is ok with usage of master branch, I would wait till there are more PRs in the branch.

But if this is considered as critical bug/feature, we can do the release now.

@cehbrecht @jorgejesus @tomkralidis  ?

**Comment by tlvu** [comment]
We have 2 projects that would benefit from this fix right now.  It's because they have recently been rebuild and we found the issue with their new build.

But if we rebuild other projects for new release, then all the new builds will be affected by this bug as well.

Ideally, we would not want to make changes to all the various projects, then revert these changes later.

I am guessing other organizations consuming pywps are in the same situation.

I am totally for bundling new features in release but for regression bug like this one, could you make an exception and release right away?  Thanks.

**Comment by huard** [comment]
Note that the current fix still passes the DefaultValue if it is None, which OWSLib does not handle. 

Not clear to me if this is desirable, since None is not a float per say. In other words, this fix does not entirely solve the original issue. I've seen similar issues with integers having a default set to inf. Should PyWPS enforce the rule that default values should be convertible to their type, or is this something left to the client ?

**Comment by huard** [comment]
Sorry, my bad, I was confused. Everything looks ok.

**Comment by jachym** [comment]
Ok, will do the release

**Comment by jachym** [comment]
I hope, I managed it well https://pypi.org/project/pywps/4.2.3/

**Pull request merged**
