### PR TITLE
updated scheduler extension

### PR DESCRIPTION
**Pull request by cehbrecht**
# Overview

This PR updates the scheduler extension. It replaces `dill` by a json dump/load to transfer the job status to the scheduler working nodes. 

It has been tested with slurm. See the updated scheduler docker demo:
https://github.com/bird-house/birdhouse-docker-images/tree/master/pywps-scheduler-demo

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x ] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x ] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@tommygod3 maybe you like to try it on your side. There are probably still issues which we can fix in this PR.

**Comment by tommygod3** [comment]
@cehbrecht Will have a look

**Comment by tommygod3** [comment]
@cehbrecht Tested on SLURM and it works :)

**Comment by cehbrecht** [comment]
@tommygod3 cool :) Thanks for trying it :)

**Comment by tommygod3** [comment]
Think it is safe to say this would close #480

**Comment by cehbrecht** [comment]
@tommygod3 done.

**Pull request merged**
