### PR TITLE
Adapt config from environmental variables (CGI-proof)

### PR DESCRIPTION
**Pull request by deduikertjes**
This pull request is a more unobtrusive redo of https://github.com/geopython/pywps/issues/40 .
It should work under CGI and not break things either.

### CODE REVIEW

**Comment by tomkralidis** [comment]
@deduikertjes FYI master branch is now repurposed (see http://lists.osgeo.org/pipermail/pywps-dev/2016-February/000488.html for more info).  If applicable, please issue this PR against branch `pywps-3.2`.

**Comment by deduikertjes** [comment]
Tom,

Before I go trough all troubles of trying to recreate this pull request on branch pywps-3.2 I'd like to know if it ever will be considered for merging? Otherwise it is just a waist of time.

**Comment by tomkralidis** [comment]
cc @jachym 

@deduikertjes good question.  At this point if you'd like to see this in 3.2.x then please provide an updated PR against that branch and it will be merged.  Else the way forward is master branch.

**Comment by jachym** [comment]
Hi - it's my fault, I was not able to get to this sooner

sorry @deduikertjes

**Pull request closed without merging**
