### PR TITLE
Adds an autoprocess Sphinx directive

### PR DESCRIPTION
**Pull request by huard**
Adds an autoprocess Sphinx directive allowing pywps Processes to be documented automatically.

# Overview

This PR registers a Sphinx directive called autoprocess that allows developers to automate the documentation of pywps processes. To see how this works, simply run `make html` and browse in the built documentation to the bottom of the Processes page. A test process exercising all the possible inputs and outputs is included, as well as instructions on how to use it for third-party packages. 

# Related Issue / Discussion

Currently, pywps developers have to manually write documentation for their processes, while all the information is available within the Process subclasses. 

# Additional Information

- Adds "six" to the dev requirements. Could possibly be removed.
- Requires minor changes to the Sphinx conf.py file. 

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard 
It is not your fault ... but in the comments of pywps code and in the docs are false class references (these were not refactored). This caused a sphinx build error at least on python 3:

*  `pywps.app.WPSResponse` is now `pywps.response.WPSResponse`
* `pywps.app.WPSResponse.STATUS` is now `pywps.response.status.STATUS`

I can provide an additional patch for it.

**Comment by ldesousa** [comment]
Thank you @huard for this contribution and again apologies for how long it took to merge. I understand you developed an extension to PyWPS with this functionality, perhaps you can definitly merge it with the core PyWPS. This will part of release 4.2.0.

**Comment by huard** [comment]
Thanks ! To be clear, the PR is an extension to sphinx, allowing pywps processes to be automatically documented by scraping information from the process and its inputs/outputs. 

We're currently using the same extension, but installed from an independent repo. Having it integrated into pywps makes more sense. See https://ouranosinc.github.io/pavics-sdi/processes/basic_climate.html for example, where the process documentation was generated by inserting 
```
.. autoprocess:: package.module.ProcessSubClass
```
Let me know if you hit any problem with it, will be happy to fix.

**Comment by jachym** [comment]
Ok, it looks ok, can we merge?

**Pull request merged**
