### PR TITLE
Implements explicit URL handling

### PR DESCRIPTION
**Pull request by huard**
# Overview

Adds a UrlHandler class. Previously, when users provided a URL to a ComplexInput, the file was automatically downloaded locally. With this PR, the link is instead stored in the url property and the file is only downloaded when the object's file, data or stream attributes are accessed. This allows processes using protocols such as opendap to use the url without downloading the file. 

Existing processes should not be affected because they would typically be accessing the file attribute in the _handler function. 

Note that the test coverage for ComplexOutput is somewhat thin. I suspect this PR could introduce bugs related to output properties. 

Tested with emu. 

# Related Issue / Discussion
Issue #352 

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
I have double-checked this PR with [Emu](https://github.com/bird-house/emu) and it works. I have added a new process `ncmeta` to Emu which uses the `url` property introduced by this PR:
https://github.com/bird-house/emu/blob/61a151dc8ec7dfb4d71da548e1607ff6b4152a2d/emu/processes/wps_ncmeta.py#L54

**Comment by cehbrecht** [comment]
@huard I have a comment to this PR and OpenDAP but I will add this to issue #152 ... for a next PR to support OpenDAP.

**Comment by cehbrecht** [comment]
@huard Are you happy with the current state of this PR? I could pull it in so we can bring in the remaining steps with new PRs.

**Comment by cehbrecht** [comment]
@huard travis is complaining about imports. You probably need to use Python 2/3 compatible imports:
https://github.com/geopython/pywps/blob/master/pywps/_compat.py

**Comment by jachym** [comment]
Can we have the commits merged into one commit?

**Comment by jachym** [comment]
I was running  integration tests at `pywps-demo` and it seems to be OK too. 

Do we need to update documentation too? @huard Just few notes to this topic?

**Comment by jachym** [comment]
OK, once https://travis-ci.org/geopython/pywps/jobs/420109895 is fixed, we can merge

**Comment by huard** [comment]
Done. Please review the changes to the docs. I've deleted a paragraph that I think was outdated (it said the file attribute returned a file object).

**Comment by cehbrecht** [comment]
@jachym I pull it in. We can adapt things later if necessary.

**Comment by cehbrecht** [comment]
@huard merged. Thanks :)

**Pull request merged**
