### PR TITLE
debian fixes

### PR DESCRIPTION
**Pull request by khosrow**
Fixed debian packaging. Builds for Ubuntu 14.04 and installs ok.

* binary package renamed to 'python-pywps'
* cleaned up debian directory

### CODE REVIEW

**Comment by tomkralidis** [comment]
thanks @khosrow

**Comment by jachym** [comment]
Hi, thanks @khosrow , good work.

Just asking is RELEASE.howto file updated too? AFAIK changelog has to be edited, before new release (?)

Thanks

**Comment by khosrow** [comment]
Hi @jachym 
I can't find the RELEASE.howto file, but I can certainly create it and commit to the repo. Any specific format you'd like to have in the document (not asking about .md or .rst)?

**Comment by tomkralidis** [comment]
How about we use the PyWPS wiki to document release packaging?  (external example: https://github.com/geopython/pycsw/wiki/Release-Packaging).  Proposing https://github.com/geopython/pywps/wiki/ReleasePackaging with section (`Debian Packaging`)

**Comment by jachym** [comment]
@tomkralidis @khosrow hmm.. maybe wiki will do

**Comment by tomkralidis** [comment]
Let's use https://github.com/geopython/pywps/wiki/ReleasePackaging as an interim step while we sort out / harden our release / packaging / distribution story.

**Comment by khosrow** [comment]
Updated the wiki as discussed.

**Comment by tomkralidis** [comment]
Thanks much @khosrow

**Pull request merged**
