### PR TITLE
Add AWS S3 Storage option + Process Status Store uses StorageAbstract

### PR DESCRIPTION
**Pull request by roarmstrong**
# Overview
This Pull Request enables support for Amazon Web Services S3 cloud storage as a StorageAbstract compatible option.

This PR also moves the Process Status Store to use StorageAbstract. This allows the status to be stored in a file / S3 object / database / etc.

StorageAbstract has had additional methods added to it to support storing arbitrary data which is used in status storage. StorageAbstract compatible classes can now be created using a StorageBuilder which will construct a storage object based on the server configuration.

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute AWS S3 storage support to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [ ] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@roarmstrong Thanks for the contribution. I have not really checked it yet, but it is useful to have different storage backends. I would like to collect some comments by the pywps team if the design fits.

**Comment by jachym** [comment]
Hi, support for S3 was always one of my dreams - thank you for your contribution.

The code seems well structured and ok to me. I'm just missing updated documentation, so it would actually be used (?)

**Comment by roarmstrong** [comment]
> Hi, support for S3 was always one of my dreams - thank you for your contribution.
> 
> The code seems well structured and ok to me. I'm just missing updated documentation, so it would actually be used (?)

Hi @jachym, thanks for the feedback, I've started updating the documentation, please let me know if there are any specifics you would like to see.

**Comment by jachym** [comment]
hi @roarmstrong please, just update the configuration section, so that users can find out, how to use it correctly

and maybe add few words to external-tools chapter

many thanks!

**Comment by roarmstrong** [comment]
Hi @jachym , I've added some example default config and some information into the docs folder under 'storage'.

**Comment by jachym** [comment]
Beautiful, I'm adding it to master - many thangs 

Just for the record: travis is complaining about python 2.7 - I'm silently ignoring it, since we are going to drop support for Python 2.

**Pull request merged**
