### PR TITLE
add support for Process Metadata objects

### PR DESCRIPTION
**Pull request by tomkralidis**
# Overview
This PR provides a proper class for `ows:Metadata` objects, and ensures all metadata class  properties are lists of `pywps.app.Common.Metadata` objects.
# Related Issue / Discussion
#189 
# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by cehbrecht** [comment]
@tomkralidis 
i just tried this patch. You probably want to use:

      OWS.Metadata(*dict(m))

instead of 

     OWS.Metadata(dict(m))

**Comment by tomkralidis** [comment]
@cehbrecht thanks for the info. What is the rationale again for this change?

**Comment by cehbrecht** [comment]
ah, the cause for the failure is another ... it does not like the None type which i avoided now by:

     self.href = href or ''

in `pywps.app.Common.Metadata`.

The following code will fail:

       from pywps.app.Common import Metadata
       m = Metadata('fail')
       from pywps import OWS
       OWS.Metadata(dict(m))

This code works:

       from pywps.app.Common import Metadata
       m = Metadata('pass', 'http://somewhere')
       from pywps import OWS
       OWS.Metadata(dict(m))

**Comment by tomkralidis** [comment]
@cehbrecht thanks for the info.  I propose the following instead:

```diff
diff --git a/pywps/app/Common.py b/pywps/app/Common.py
index 4ec2117..a01937e 100644
--- a/pywps/app/Common.py
+++ b/pywps/app/Common.py
@@ -26,5 +26,6 @@ class Metadata(object):
 
     def __iter__(self):
         yield '{http://www.w3.org/1999/xlink}title', self.title
-        yield '{http://www.w3.org/1999/xlink}href', self.href
+        if self.href is not None:
+            yield '{http://www.w3.org/1999/xlink}href', self.href
         yield '{http://www.w3.org/1999/xlink}type', self.type
```

This prevents outputting an empty href attribute in XML. Thoughts?

**Comment by cehbrecht** [comment]
fine :) works for me.

**Comment by tomkralidis** [comment]
@cehbrecht last question: why `OWS.Metadata(*dict(m))` and not `OWS.Metadata(dict(m))`?

**Comment by cehbrecht** [comment]
that was a mistake by myself ... i got these exceptions and i thought it should be `**dict(m)`.

**Comment by jachym** [comment]
@tomkralidis I guess, we should fix pywps-demo, right? 
https://github.com/geopython/pywps-demo/blob/master/processes/sleep.py#L36

**Comment by tomkralidis** [comment]
@jachym done in https://github.com/geopython/pywps-demo/commit/7125c22e3e2a24450e3bc970d9e7045dcc0e70fb

**Comment by jachym** [comment]
Well, it needed a bit more https://github.com/geopython/pywps-demo/commit/b10ff4c0dd6827b7be781e0c30d1244c46896ecd

Side note: IMHO this feature should be discussed more heavily before being committed. We should be in "Feature freeze" stage and the testing was IMHO not sufficient. Just my feeling.

**Comment by jachym** [comment]
He, but thank you for the feature, it's needed!

**Comment by tomkralidis** [comment]
@jachym agree.  Sorry for the oversight.

**Pull request merged**
